package co.com.iteria.naturalparksback.model;
// Generated 28/08/2018 10:39:47 PM by Hibernate Tools 4.3.1



/**
 * ApiParque generated by hbm2java
 */
public class ApiParque  implements java.io.Serializable {


     private int id;
     private String name;
     private String state;
     private int capacity;
     private String status;

    public ApiParque() {
    }

    public ApiParque(int id, String name, String state, int capacity, String status) {
       this.id = id;
       this.name = name;
       this.state = state;
       this.capacity = capacity;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public String getStrJson(){
        String str; 
        
        str =  "{\n\"id\": "+this.id+",\n\"name\": \""+this.name+"\",\n\"state\": \""+this.state+
                "\",\n\"capacity\": "+this.capacity+",\n\"status\" : \""+this.status+"\"\n}";
        
        return  str;
    }




}


