package co.com.iteria.naturalparksfront.model;
// Generated 28/08/2018 10:39:47 PM by Hibernate Tools 4.3.1

import javax.json.Json;
import javax.json.JsonObject;
import javax.ws.rs.client.Entity;




/**
 * Parque generated by hbm2java
 */
public class Parque  implements java.io.Serializable {


     private int id;
     private String name;
     private String state;
     private int capacity;
     private String status;

    public Parque() {
    }

    public Parque(int id, String name, String state, int capacity, String status) {
       this.id = id;
       this.name = name;
       this.state = state;
       this.capacity = capacity;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public static Parque parkFromJSON(JsonObject val){
        
        int id = val.getInt("id");
        String name = val.getString("name");
        String state  = val.getString("state");
        int capacity = val.getInt("capacity");
        String status = val.getString("status");
        
        Parque p = new Parque(id, name, state, capacity, status);
        
        return p;         
    }
   
    
    public Entity toJson(){
        
        Entity payload = Entity.json(this.getStrJson());
        return payload;
    }
    
    public String getStrJson(){
        String str; 
        
        str =  "{\n\"id\": "+this.id+",\n\"name\": \""+this.name+"\",\n\"state\": \""+this.state+
                "\",\n\"capacity\": "+this.capacity+",\n\"status\" : \""+this.status+"\"\n}";
        
        return  str;
    }




}


